
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# https://wiki.hypr.land/Configuring/Keywords/#executing

exec-once = waybar &
exec-once = swaync
exec-once = hyprctl setcursor CustomCursors 22

exec-once = flatpak run com.github.wwmm.easyeffects --service-mode --hide-window

exec-once = /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1

exec-once = flatpak run com.discordapp.Discord --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --start-minimized

exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Mint-Y-Dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'CustomCursors'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Cascadia Code'