export function printHelp(): void {
  console.log(
    [
      "pr — GitHub pull request helper",
      "",
      "Usage:",
      "  pr [command]",
      "",
      "Commands:",
      "  create         Prepare or open a new pull request for this branch",
      "  update         Refresh PR title & body from current diff (agent + gh pr edit)",
      "  review         Run agent on a PR, preview comment, then gh pr review --comment",
      "  (default)      Prints one line (e.g. updating PR #N with URL, or creating a PR from this branch),",
      "                   then runs that command; a GitHub PR URL as the first arg prints a review line and runs `pr review <url>`.",
      "",
      "Work (optional):",
      "  PR_CLI_WORK=true           NOVACORE title prefix + …/create|update|review/prompt.work.md beside each prompt.md",
      "  PR_CLI_WORKSPACE_ROOT=…    Anchor for agent cwd (default os.tmpdir()); workspaces are <anchor>/pr-cli/<repo>/<branch>/",
      "",
      "Options:",
      "  --print-prompt   After workspace prefetch, print the full resolved agent prompt to stdout and exit",
      "                   (no agent). Combinable with --opus / --codex. With no subcommand, a short status line prints,",
      "                   then the chosen command runs. Put flags after a PR URL when using a URL without `review`.",
      "  --no-agent       Prepare the workspace the same way, but do not run the Cursor agent. create/review",
      "                   write a small stub PR.md for you to edit; update seeds PR.md and keeps the GitHub snapshot in CURRENT.md.",
      "  --dir            Print the agent workspace directory on stderr; otherwise the path is not printed.",
      "  --opus           Run the Cursor agent with the Opus model (claude-opus-4-7-high).",
      "  --codex          Run with Codex 5.3 (gpt-5.3-codex).",
      "  (default model)  If neither is set, uses composer-2-fast (agent --list-models).",
      "  -h, --help       Show this message",
    ].join("\n"),
  );
}
