export function printHelp(): void {
  console.log(
    [
      "pr — GitHub pull request helper",
      "",
      "Usage:",
      "  pr [command]",
      "",
      "Commands:",
      "  create         Prepare or open a new pull request for this branch",
      "  update         Refresh PR title & body from current diff (agent + gh pr edit)",
      "  review         Run agent on a PR, preview comment, then gh pr review --comment",
      "  (default)      Picks create or update from open PR on this branch",
      "",
      "Work (optional):",
      "  PR_CLI_WORK=true           NOVACORE title prefix + …/create|update|review/prompt.work.md beside each prompt.md",
      "  PR_CLI_WORKSPACE_ROOT=…    Anchor for agent cwd (default os.tmpdir()); workspaces are <anchor>/pr-cli/<repo>/<branch>/",
      "",
      "Options:",
      "  --print-prompt   After workspace prefetch, print the full resolved agent prompt to stdout and exit",
      "                   (no agent). Combinable with --opus / --codex. With no subcommand, same flags infer create|update.",
      "  --no-agent       Prepare the workspace the same way, but do not run the Cursor agent. create/review",
      "                   write a small stub PR.md for you to edit; update uses the prefetched PR.md only.",
      "  --opus           Run the Cursor agent with the Opus model (claude-opus-4-7-high).",
      "  --codex          Run with Codex 5.3 (gpt-5.3-codex).",
      "  (default model)  If neither is set, uses composer-2-fast (agent --list-models).",
      "  -h, --help       Show this message",
    ].join("\n"),
  );
}
