# --- Environment Variables ---
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# --- QT Specifics ---
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct

# --- Cursors ---
env = XCURSOR_THEME,CustomCursors
env = XCURSOR_SIZE,22
env = HYPRCURSOR_THEME,CustomCursors
env = HYPRCURSOR_SIZE,22